# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zavala
subtitle: Modern Outlining
email: mo@vincode.io
description: >- # this means to ignore newlines until "baseurl:"
  A good, simple outliner for macOS and iOS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zavala.vincode.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vincode_io
github_username:  vincode-io

logo: "/assets/images/88x88.png"
repository: "vincode-io/Zavala"
twitter:
  username: "vincode_io"
og_image: "/assets/images/site-logo.png"
timezone: "US/Central"

minimal_mistakes_skin: "dirt"

paginate: 5
paginate_path: "/blog/page:num"

author:
  name: "Maurice Parker"
  avatar: "/assets/images/avatar.jpg"
  bio: "I'm an Open Source developer with a soft spot for OPML files."
  location: "Centerville, IA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mo@vincode.io"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://vincode.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/vincode_io"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      show_date: true 
      read_time: true

# Build settings
#theme: minima
#theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache

include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
